#!/usr/bin/env python3
"""Generate deterministic radial asteroid contours from runtime sprite alpha masks."""

from pathlib import Path
import argparse
import math

import numpy as np
from PIL import Image, ImageDraw
from scipy import ndimage


ROOT = Path(__file__).resolve().parents[1]
SPRITES = ROOT / "public" / "assets" / "sprites"
OUTPUT = ROOT / "src" / "game" / "simulation" / "AsteroidShapeProfiles.generated.ts"
DISPLAY_DIAMETER_IN_RADII = 2.35
SAMPLE_COUNT = 48
ALPHA_THRESHOLD = 128

MATERIALS = {
    "rocky": "rocky",
    "carbonaceous": "carbon",
    "icy": "icy",
    "metallic": "metallic",
}
SHAPES = ("boulder", "shard", "rubble", "wedge")


def sample_contour(path: Path) -> list[tuple[float, float]]:
    image = Image.open(path).convert("RGBA")
    alpha = np.array(image)[:, :, 3]
    labels, count = ndimage.label(alpha >= ALPHA_THRESHOLD)
    component_sizes = np.bincount(labels.ravel())
    component_sizes[0] = 0
    largest_component = int(component_sizes.argmax()) if count > 0 else 0
    mask = labels == largest_component
    centre_x = (image.width - 1) / 2
    centre_y = (image.height - 1) / 2
    maximum_radius = math.hypot(image.width, image.height) / 2
    points: list[tuple[float, float]] = []

    for index in range(SAMPLE_COUNT):
        angle = index * math.tau / SAMPLE_COUNT
        direction_x = math.cos(angle)
        direction_y = math.sin(angle)
        last_visible = 0.0
        step = 0.5
        radius = 0.0
        while radius <= maximum_radius:
            pixel_x = round(centre_x + direction_x * radius)
            pixel_y = round(centre_y + direction_y * radius)
            if pixel_x < 0 or pixel_x >= image.width or pixel_y < 0 or pixel_y >= image.height:
                break
            if mask[pixel_y, pixel_x]:
                last_visible = radius
            radius += step
        normalized_radius = last_visible * DISPLAY_DIAMETER_IN_RADII / image.width
        points.append((direction_x * normalized_radius, direction_y * normalized_radius))
    return points


def format_profile(points: list[tuple[float, float]], indent: str) -> str:
    rendered = [f"{{ x: {x:.4f}, y: {y:.4f} }}" for x, y in points]
    lines = []
    for start in range(0, len(rendered), 4):
        lines.append(indent + ", ".join(rendered[start : start + 4]) + ",")
    return "\n".join(lines)


def sprite_path(resolution: str, filename_material: str, index: int) -> Path:
    suffix = "_v1.png" if filename_material == "rocky" and resolution == "standard" else \
        "_v3.png" if resolution == "standard" else "_colossal_v1.png"
    return SPRITES / f"asteroid_{filename_material}_{index}{suffix}"


def render_previews(
    preview_dir: Path,
    profiles: dict[tuple[str, str, str], list[tuple[float, float]]],
) -> None:
    preview_dir.mkdir(parents=True, exist_ok=True)
    for resolution in ("standard", "colossal"):
        for material, filename_material in MATERIALS.items():
            sprites: list[Image.Image] = []
            for index, shape in enumerate(SHAPES):
                path = sprite_path(resolution, filename_material, index)
                sprite = Image.open(path).convert("RGBA")
                draw = ImageDraw.Draw(sprite)
                centre_x = (sprite.width - 1) / 2
                centre_y = (sprite.height - 1) / 2
                contour = [
                    (
                        centre_x + x * sprite.width / DISPLAY_DIAMETER_IN_RADII,
                        centre_y + y * sprite.width / DISPLAY_DIAMETER_IN_RADII,
                    )
                    for x, y in profiles[(resolution, material, shape)]
                ]
                contour.append(contour[0])
                draw.line(contour, fill=(255, 146, 71, 255), width=max(2, sprite.width // 150))
                sprites.append(sprite)
            tile_width = sprites[0].width
            tile_height = sprites[0].height
            sheet = Image.new("RGBA", (tile_width * 2, tile_height * 2), (5, 10, 14, 255))
            for index, sprite in enumerate(sprites):
                sheet.alpha_composite(sprite, ((index % 2) * tile_width, (index // 2) * tile_height))
            output = preview_dir / f"{resolution}-{material}-contours.png"
            sheet.convert("RGB").save(output, optimize=True)
            print(f"Wrote {output}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--preview-dir", type=Path)
    args = parser.parse_args()
    profiles: dict[tuple[str, str, str], list[tuple[float, float]]] = {}
    lines = [
        "// Generated by scripts/generate-asteroid-contours.py. Do not hand-edit.",
        "import type { Vector2 } from './Vector2';",
        "",
        "export type AsteroidContourResolution = 'standard' | 'colossal';",
        "export type AsteroidContourMaterial = 'rocky' | 'carbonaceous' | 'icy' | 'metallic';",
        "export type AsteroidContourShape = 'boulder' | 'shard' | 'rubble' | 'wedge';",
        "",
        "export const generatedAsteroidShapeProfiles: Record<",
        "  AsteroidContourResolution,",
        "  Record<AsteroidContourMaterial, Record<AsteroidContourShape, readonly Vector2[]>>",
        "> = {",
    ]

    for resolution in ("standard", "colossal"):
        lines.append(f"  {resolution}: {{")
        for material, filename_material in MATERIALS.items():
            lines.append(f"    {material}: {{")
            for index, shape in enumerate(SHAPES):
                path = sprite_path(resolution, filename_material, index)
                points = sample_contour(path)
                profiles[(resolution, material, shape)] = points
                lines.append(f"      {shape}: [")
                lines.append(format_profile(points, "        "))
                lines.append("      ],")
            lines.append("    },")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT}")
    if args.preview_dir is not None:
        render_previews(args.preview_dir, profiles)


if __name__ == "__main__":
    main()
