#!/usr/bin/env python3
"""Remove the baked checkerboard and derive the runtime ship collision contour."""

from __future__ import annotations

from collections import deque
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path("/Users/mhoeppner/Downloads/Hauler.png")
OUTPUT = ROOT / "public/assets/sprites/ship_hauler_v1.png"
PROFILE_OUTPUT = ROOT / "src/game/simulation/ShipShapeProfile.generated.ts"

DISPLAY_WIDTH = 42.0
DISPLAY_HEIGHT = 76.0
PROFILE_SAMPLES = 96
PADDING = 8


def is_background_candidate(pixel: tuple[int, int, int]) -> bool:
    red, green, blue = pixel
    return min(red, green, blue) >= 225 and max(red, green, blue) - min(red, green, blue) <= 22


def connected_background(image: Image.Image) -> set[tuple[int, int]]:
    rgb = image.convert("RGB")
    width, height = rgb.size
    queue: deque[tuple[int, int]] = deque()
    visited: set[tuple[int, int]] = set()

    for x in range(width):
        queue.append((x, 0))
        queue.append((x, height - 1))
    for y in range(height):
        queue.append((0, y))
        queue.append((width - 1, y))

    while queue:
        x, y = queue.popleft()
        if x < 0 or y < 0 or x >= width or y >= height or (x, y) in visited:
            continue
        if not is_background_candidate(rgb.getpixel((x, y))):
            continue
        visited.add((x, y))
        queue.append((x - 1, y))
        queue.append((x + 1, y))
        queue.append((x, y - 1))
        queue.append((x, y + 1))
    return visited


def make_transparent_sprite(image: Image.Image) -> tuple[Image.Image, tuple[int, int, int, int]]:
    rgba = image.convert("RGBA")
    background = connected_background(image)
    for x, y in background:
        red, green, blue, _ = rgba.getpixel((x, y))
        rgba.putpixel((x, y), (red, green, blue, 0))

    alpha = rgba.getchannel("A")
    bounds = alpha.getbbox()
    if bounds is None:
        raise RuntimeError("No opaque ship pixels remained after checkerboard removal.")
    left, top, right, bottom = bounds
    crop = (
        max(0, left - PADDING),
        max(0, top - PADDING),
        min(rgba.width, right + PADDING),
        min(rgba.height, bottom + PADDING),
    )
    return rgba.crop(crop), crop


def sample_profile(sprite: Image.Image) -> list[tuple[float, float]]:
    alpha = sprite.getchannel("A")
    width, height = sprite.size
    centre_x = width / 2
    centre_y = height / 2
    maximum_radius = (DISPLAY_WIDTH**2 + DISPLAY_HEIGHT**2) ** 0.5
    points: list[tuple[float, float]] = []

    import math

    for index in range(PROFILE_SAMPLES):
        angle = index / PROFILE_SAMPLES * math.tau
        direction_x = math.cos(angle)
        direction_y = math.sin(angle)
        outermost = 0.0
        step = 0.12
        radius = 0.0
        while radius <= maximum_radius:
            world_x = direction_x * radius
            world_y = direction_y * radius
            image_x = round(centre_x + world_x / DISPLAY_WIDTH * width)
            image_y = round(centre_y + world_y / DISPLAY_HEIGHT * height)
            if image_x < 0 or image_y < 0 or image_x >= width or image_y >= height:
                break
            if alpha.getpixel((image_x, image_y)) >= 32:
                outermost = radius
            radius += step
        points.append((direction_x * outermost, direction_y * outermost))
    return points


def write_profile(points: list[tuple[float, float]], crop: tuple[int, int, int, int]) -> None:
    source_anchors = {
        "port": (355, 625),
        "starboard": (899, 625),
        "ventral": (620, 997),
        "cargoBay": (620, 588),
    }
    left, top, right, bottom = crop
    width = right - left
    height = bottom - top

    def convert(point: tuple[int, int]) -> tuple[float, float]:
        x, y = point
        return (
            ((x - left) / width - 0.5) * DISPLAY_WIDTH,
            ((y - top) / height - 0.5) * DISPLAY_HEIGHT,
        )

    anchors = {name: convert(point) for name, point in source_anchors.items()}
    lines = [
        "// Generated by scripts/prepare-hauler-sprite.py from the user-supplied Hauler.png.",
        "import type { Vector2 } from './Vector2';",
        "",
        f"export const SHIP_DISPLAY_WIDTH = {DISPLAY_WIDTH:.1f};",
        f"export const SHIP_DISPLAY_HEIGHT = {DISPLAY_HEIGHT:.1f};",
        "",
        "export const generatedShipContour: readonly Vector2[] = [",
    ]
    lines.extend(f"  {{ x: {x:.4f}, y: {y:.4f} }}," for x, y in points)
    lines.extend(
        [
            "];",
            "",
            "export const generatedShipAnchors = {",
            *[
                f"  {name}: {{ x: {point[0]:.4f}, y: {point[1]:.4f} }},"
                for name, point in anchors.items()
            ],
            "} as const;",
            "",
        ]
    )
    PROFILE_OUTPUT.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    source = Image.open(SOURCE)
    sprite, crop = make_transparent_sprite(source)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    sprite.save(OUTPUT)
    points = sample_profile(sprite)
    write_profile(points, crop)
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({sprite.width}x{sprite.height})")
    print(f"Wrote {PROFILE_OUTPUT.relative_to(ROOT)} ({len(points)} contour points)")


if __name__ == "__main__":
    main()
