export const tuning = {
  simulationHz: 60,
  maxFrameDeltaMs: 250,
  maxSimulationStepsPerFrame: 8,

  portraitShipAnchorY: 0.74,
  landscapeShipAnchorY: 0.70,
  cameraLookAheadMin: 40,
  cameraLookAheadMax: 120,
  cameraZoomPortrait: 1.55,
  cameraZoomLandscape: 1.28,
  cameraZoomDesktop: 1.38,
  cameraZoomResponse: 7,
  cameraMiningZoomMultiplier: 1.08,

  tiltDeadZoneDegrees: 3,
  tiltFullInputDegrees: 20,
  tiltSmoothingMs: 120,

  safeContactSpeed: 5,
  minorDamageSpeed: 12,
  seriousDamageSpeed: 22,

  ship: {
    radius: 38,
    dryMass: 12,
    initialCargoMass: 0,
    cargoCapacity: 20,
    maxHull: 100,
    fuelCapacity: 100,
    initialFuel: 100,
    forwardThrust: 90,
    auxiliaryForwardThrust: 30,
    reverseThrust: 52,
    lateralThrust: 52,
    rotationalAcceleration: 3.8,
    maxAngularSpeed: 2.4,
    angularDamping: 2.0,
    forwardFuelPerSecond: 0.72,
    reverseFuelPerSecond: 0.48,
    lateralFuelPerSecond: 0.42,
    rotationalFuelPerSecond: 0.08,
    collisionRestitution: 0.12,
    maxCollisionDamage: 30,
    internalSafetySpeedClamp: 150,
    startingDrones: 1,
  },

  asteroid: {
    count: 42,
    baseVerySmallRadius: 12,
    sizeScale: {
      'very-small': 1,
      small: 2,
      medium: 5,
      large: 10,
      'very-large': 25,
    },
    sizeVariation: 0.12,
    verySmallShare: 0.40,
    smallShare: 0.30,
    mediumShare: 0.18,
    largeShare: 0.09,
    minSpawnDistance: 330,
    maxSpawnDistance: 1500,
    meanDriftX: 0.35,
    meanDriftY: -0.15,
    velocityVariation: 1.35,
    minSpin: -0.09,
    maxSpin: 0.09,
    playerSpawnExclusionPadding: 120,
    asteroidSpawnPadding: 10,
    spawnPlacementAttempts: 320,
    collisionRestitution: 0.68,
    fragmentationMinRelativeSpeed: 6,
    fragmentationGuaranteedSpeed: 18,
    fragmentationMinParentRadius: 14,
    fragmentationMaxGeneration: 2,
    fragmentationGraceSeconds: 0.85,
    fragmentationResourceRetention: 0.94,
    fragmentationMaxAsteroids: 72,
    structuralIntegrity: {
      'very-small': 1,
      small: 2.5,
      medium: 6,
      large: 18,
      'very-large': 60,
    },
  },

  station: {
    radius: 110,
    positionX: 0,
    positionY: 115,
    asteroidExclusionPadding: 1000,
    dockingDistance: 166,
    dockingMaxRelativeSpeed: 2.5,
    dockingStabilizeSeconds: 1.5,
    dockedShipX: 0,
    dockedShipY: -5,
  },

  trader: {
    radius: 38,
    cruiseSpeed: 36,
    acceleration: 9,
    dockingSeconds: 5,
    replanSeconds: 4,
    waypointTolerance: 12,
    arrivalRadius: 4,
    dockLateralOffset: 145,
  },

  mining: {
    distanceFromSurface: 70,
    armRelativeSpeed: 6.5,
    armSeconds: 0.6,
    pauseDistance: 110,
    emergencyRecallSpeed: 8,
    droneTravelSpeed: 60,
    extractSeconds: 2.4,
    payloadPerTrip: 3,
    launchSpacingSeconds: 0.22,
    debrisIntervalSeconds: 2.2,
    debrisMinSpeed: 0.65,
    debrisMaxSpeed: 2.2,
    debrisLifetimeSeconds: 16,
  },

  navigation: {
    asteroidStandoffSurface: 26,
    stationStandoffSurface: 12,
    positionGain: 0.32,
    maximumApproachSpeed: 20,
    finalApproachSpeed: 1.3,
    headingGain: 2.7,
    angularVelocityGain: 0.72,
    thrustDeltaVForFullInput: 4.5,
    directOverrideThreshold: 0.12,
    autopilotGridSize: 48,
    autopilotSearchMargin: 560,
    autopilotSafetyMargin: 20,
    autopilotPredictionSeconds: 5,
    autopilotReplanSeconds: 2,
    autopilotStableReplanSeconds: 8,
    autopilotRouteTrackingTolerance: 16,
    autopilotWaypointTolerance: 5,
    autopilotArrivalRadius: 32,
    autopilotCruiseSpeed: 50,
    autopilotMinimumCornerSpeed: 3,
    autopilotCornerDeceleration: 0.7,
    autopilotMomentumMarginPerSpeed: 1.1,
    autopilotMomentumMarginMax: 52,
    autopilotMaxShortcutDistance: 320,
    autopilotMaxNodes: 14_000,
  },

  sectorHalfExtent: 2400,
  velocityVectorLengthSpeed: 100,
  velocityVectorMaxLength: 88,
  velocityVectorWarningSpeed: 130,
  velocityVectorRedSpeed: 140,
  impactMessageSeconds: 2.8,
  collisionRearmDistance: 1.5,
} as const;

export type Tuning = typeof tuning;
